name: Deploy to Hetzner (FTPS)

on:
  push:
    branches: [ production ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          local-dir: ./          # deploy the repo root
          exclude: |             # keep things tidy
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/*.md
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false
